@startuml connect wallet sequence
autonumber

User -> ConnectButton: clicks
ConnectButton -> WalletStore: Dispatch(CONNECT)
WalletStore -> WalletSaga: connectWallet()

== SAGA OPS == 

WalletSaga -> WalletSaga: ActionEffectConnectWallet()
WalletSaga -> WalletSaga: HandleStateInitRequested()

WalletSaga -> EthAPI: isWalletDetected()

alt wallet detected
WalletSaga -> WalletSaga: HandleStateNetworkRequested()

WalletSaga -> EthAPI: isNetworkSupported()

alt network supported
WalletSaga -> WalletSaga: HandleUnlockRequested()
else network not supported
WalletSaga -> WalletSaga: HandleStateNetworkSwitchRequested()
end

else wallet not detected
WalletSaga -> WalletSaga: HandleStateNotSupported()
end
@enduml