# This is a basic workflow to help you get started with Actions

name: CI2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: dapp
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npx create-react-app test1 --template file:./dapp
      - run: npm ci
        working-directory: test1
      - run: npm run lint
        working-directory: test1
      - run: npm run test
        working-directory: test1
      - run: npm run build
        working-directory: test1
